// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjSxAb1Tb_sRV8Gg_q_m4Tdw78nPuQemI',
    appId: '1:340159068661:web:56cd7dfcb63dfe47e008bc',
    messagingSenderId: '340159068661',
    projectId: 'spenly-97b73',
    authDomain: 'spenly-97b73.firebaseapp.com',
    storageBucket: 'spenly-97b73.firebasestorage.app',
    measurementId: 'G-2R7QT5K6D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvyS4qVHzMXUu5RlXv7mCxg9NvxPoZJEE',
    appId: '1:340159068661:android:bb9c8710d2ecd8dbe008bc',
    messagingSenderId: '340159068661',
    projectId: 'spenly-97b73',
    storageBucket: 'spenly-97b73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCJFJ01Rx_Qat5XyYhF8BW0ZtK6MGSLkw',
    appId: '1:340159068661:ios:ad2bf382a90ca741e008bc',
    messagingSenderId: '340159068661',
    projectId: 'spenly-97b73',
    storageBucket: 'spenly-97b73.firebasestorage.app',
    iosBundleId: 'com.example.spendee',
  );
}
